title: <h2 align="left">Hi 👋! My name is SYEDA SHAHRIN
description: and I'm AN ENGINEER
logo: docs/assets/Reflection 1.pdf
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
logo: docs/assets/Screenshot (513).png

